### ISSUE TITLE
Error backtracking pages throughout the site

### ISSUE THREAD

**Issue by iamdarkle** [davwheat/flarum-ext-ads#3]
I've been experiencing a slightly annoying error for a while now that I had no idea where it was coming from, I've been testing and seem to have located it in Ad Units.

![WEjONAHFFo](https://user-images.githubusercontent.com/15818451/145144401-868f93b5-48fa-4898-b236-4af105f10091.gif)

In the gif you can see quite well what is happening, when we first enter the web / reload completely if we click any link to go back we have to press the back button 3 times to finally happen. After doing this if for example we go back to the profile does not happen anymore, we would have to completely reload the web to happen again.

**Comment by davwheat** [comment]
I've just tried but can't seem to reproduce this. Maybe it's this combined with another extension which causes the issue?

I _think_ if you're still having this issue, disabling the footer ad will prevent this happening, though.

**Comment by iamdarkle** [comment]
Sorry for the long time, I have finally located this bug, although it's related to this extension, it's actually caused by another extension that should fix it from its side, but as it is no longer public I don't think it's worth to go into it in depth. Closing here 🙂
